- name: Backend setup
  hosts: all
  become: yes
  tasks:
    - name: Setup NodeJS repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: latest

    - name: User addition
      ansible.builtin.user:
        name: expense

    - name: cleaning old content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Creating the directory
      ansible.builtin.file:
        path: /add
        state: directory

    - name: Download and extract the file
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: Install Node js & Change the directory
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: copying the file
      ansible.builtin.copy:
        src: /backend.conf
        dest: /etc/systemd/system/backend.service

    - name: Start backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes

    - name: install the mysql
      ansible.builtin.dnf:
        name: mysql
        state: present

    - name: load the schema
      ansible.builtin.shell: mysql -h mysql.saujpoo.online -uroot -pExpenseApp@1 < /app/schema/backend.sql