- name: cleaning old content
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: Creating the directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory

- name: Download and extract the file
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/backend.zip
    dest: "{{ app_loc }}"
    remote_src: yes