
- name: verify the nodejs
  ansible.builtin.shell: type npm
  register: npm
  ignore_errors: yes

- name: Install nodejs
  ansible.builtin.shell:  curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  when: npm.rc !=0

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    when: npm.rc !=0

- name: copying the file
  ansible.builtin.copy:
  src: backend.conf
  dest: /etc/systemd/system/backend.service

- name: User addition
  ansible.builtin.user:
    name: expense



- name: Install Node js dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: install the mysql
  ansible.builtin.dnf:
    name: mysql



- name: Start backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: load the schema
  ansible.builtin.shell: mysql -h mysql.saujpoo.online -uroot -pExpenseApp@1 < /app/schema/backend.sql