  - name: Set hostname
    ansible.builtin.shell: set-hostname backend

  - name: Verify NodeJs
    ansible.builtin.shell: type npm
    register: npm


  - name: Read Npm
    ansible.builtin.debug:
      msg: "{npm}"


  - name: Install Nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: latest
    when: npm.rc !=0
    #dnf install nodejs -y &>>$log_file

  - name: Copy Backend Service file
    ansible.builtin.template:
      src: backend.service
      dest: /etc/systemd/system/backend.service

    #cp backend.service /etc/systemd/system/backend.service &>>$log_file

  - name: Add Application user
    ansible.builtin.user:
      name: expense


    #useradd expense &>>$log_file

  - name: Import a role
    ansible.builtin.import_role:
      name: common
      tasks_from: app_prereq.yml

  - name: Download Dependencies
    ansible.builtin.shell: npm install
    args:
      chdir: /app



  - name: Install MySQL Client
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: Starting Backend Service
    ansible.builtin.service:
      name: backend
      state: restarted
      enabled: yes
      daemon-reload: yes

  - name: Load Schema
    ansible.builtin.shell: mysql -h 172.31.26.12 -uroot -pExpenseApp@1 < /app/schema/backend.sql



