
  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: Placing Expense Config file in Nginx
    ansible.builtin.template:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: Import a role
    ansible.builtin.import_role:
      name: common
      tasks_from: app_prereq.yml


  - name: Starting Nginx Service
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes